### ISSUE TITLE
[Feature Request] Could there be an option to include the video's title as well?

### ISSUE THREAD

**Issue by mcx** [badabing2005/joplin-plugin-ytinsert#1]
Thanks for the plugin! It has been really useful. 

Just wondering if there is a way to have the "Insert YouTube Video" option also include the video title underneath the picture?

Also, if you posted it to the [Joplin forum](https://discourse.joplinapp.org/c/plugins/18), I bet it'll gain a lot more users!

**Comment by badabing2005** [comment]
See release 1.0.1
YouTube doesn't provide a simple API to fetch video details without authentication, so this workaround extracts the title from HTML meta tags.
If the Title is not there or it changes, the functionality would break.

**Comment by mcx** [comment]
Amazingly quick! Just tested it and it works as expected. Thanks again!
