### ISSUE TITLE
Homepage link not specific enough

### ISSUE THREAD

**Issue by annoyedhumanoid** [badabing2005/joplin-plugin-ytinsert#2]
The plugin's homepage—the only hyperlink in Joplin's plugins settings pane—leads to github.com/badabing2005, leaving users to have to search for the specific repository. [Line 9 in manifest.json](https://github.com/badabing2005/joplin-plugin-ytinsert/blob/35123a0ec65acf1213b3e8a10e2b81e9803dd3f9/src/manifest.json#L9) should be `"homepage_url": "https://github.com/badabing2005/joplin-plugin-ytinsert"`.

**Comment by badabing2005** [comment]
Thanks for bringing this to my attention.
Fixed: https://github.com/badabing2005/joplin-plugin-ytinsert/releases/tag/v1.0.4

**Comment by annoyedhumanoid** [comment]
Thanks for fixing it :)
